= API : Consumir mediante código
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Consumir API
La API tiene tres endpoints para su uso. Además, al utilizar _swagger_ se puede acceder directamente mediante una interfaz gráfica para su uso manual.

=== Endpoints
Los *endpoints* son puntos de acceso o URLs específicas que se utilizan para realizar operaciones o solicitudes a través de la API. Cada endpoint está diseñado para llevar a cabo una función específica y proporciona una forma estructurada y estandarizada de interactuar con la API.

Los *endpoints* pueden recibir solicitudes, como solicitudes HTTP-GET para obtener información o solicitudes HTTP-POST para enviar datos al servidor. En resumen, los *endpoints* actúan como interfaces que permiten a los clientes (como aplicaciones o usuarios) comunicarse de manera eficiente con la API y acceder a sus recursos o servicios de manera predefinida.

[disclaimer]
----
- fred hace referencia al modelo de machine learning que clasifica a las imágenes de tumores cerebrales.

- wini hace referencia al modelo de machine learning que clasifica a las imágenes de pulmones con neumonía.

----

=== */ping*
Mediante una solicitud HTTP-GET se puede solicitar el endpoint, donde si está activo el servicio retorna un 200 y un JSON con el mensaje "API on!". Para acceder al endpoint se debe agregar al dominio donde está la API subida _/ping_. EJ: https://averiapi-4vtuhnxfba-uc.a.run.app/ping


.ejemplo_get.js
[source,javascript]
----
fetch('https://averiapi-4vtuhnxfba-uc.a.run.app/ping')
  .then(response => {
    if (response.ok) {
      // El código de estado es 200 (OK)
      console.log('Código de estado: ' + response.status);
      return response.json();
    }
----

=== */predict/fred*

Mediante una solicitud HTTP-POST se puede enviar al endpoint un Json, cual puede recibir los siguientes valores: 

- image, cual debe ser un archivo binario (imagen).

- debilidad_focal: Almacena un booleano.

- convulsiones: Almacena un booleano.

- perdida_visual: Almacena un booleano.

Retornara el % de probabilidad de cada clase del dominio. Ej:
{"glioma" : 0%,
 "meningioma" : 5%,
 "pituitary" : 0%,
 "no_tumor" : 95%}

.ejemplo_post.js
[source,javascript]
----
const formData = new FormData();
formData.append('image', imagenFile); 
formData.append('debilidad_focal', True); 
formData.append('convulsiones', False); 
formData.append('perdida_visual', True); 

// Realizar la solicitud POST a la API
fetch('https://averiapi-4vtuhnxfba-uc.a.run.app/predict/fred', {
  method: 'POST',
  body: formData
})
  .then(response => {
    if (response.ok) {
      return response.text();
    } else {
      throw new Error('Error en la solicitud');
    }
  })
  .then(data => {
    console.log('Respuesta de la API:', data);
  })
  .catch(error => {
    console.error('Error al enviar la imagen:', error);
  });
----

=== */predict/wini*

Se realiza el mismo procedimiento del modelo fred, pero con distintos campos del json y cambiando el dominio por wini: https://averiapi-4vtuhnxfba-uc.a.run.app/predict/wini.

- image: Debe ser un archivo binario (imagen).

- puntada_lateral: Almacena un booleano.

- fiebre: Almacena un booleano.

- dificultad_respiratoria: Almacena un booleano.

Retornara el % de probabilidad de cada clase del dominio. Ej:
{"pneumonia" : 1%,
 "no_pneumonia" : 99%
}

=== */feedback/fred*
ruta = https://averiapi-4vtuhnxfba-uc.a.run.app/feedback/fred.

Mediante una solicitud HTTP-POST se puede enviar al endpoint un Json, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- glioma: Almacena un booleano.
- meningioma: Almacena un booleano.
- pituitary: Almacena un booleano.
- no_tumor: Almacena un booleano.

Retornara un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED}: En caso de que los valores del json esten correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4.

- {"message" : "ERROR! Values Null"}: En caso de que algún valor del json sea nulo.

- {"message": "ERROR! all values is false"}: En caso de que todos los campos del json que almacenan booleanos sean false.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del json que almacenan booleanos sean true.

Se consume de la misma manera del endpoint predict/fred cambiando los campos y el endpoint.

=== */feedback/wini*
ruta = https://averiapi-4vtuhnxfba-uc.a.run.app/feedback/wini

Mediante una solicitud HTTP-POST se puede enviar al endpoint un Json, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- pneumonia: Almacena un booleano.
- no_pneumonia: Almacena un booleano.

Retornara un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED}: En caso de que los valores del json esten correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4.

- {"message" : "ERROR! Values Null"}: En caso de que algún valor del json sea nulo.

- {"message": "ERROR! all values is false"}: En caso de que todos los campos del json que almacenan booleanos sean false.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del json que almacenan booleanos sean true.

Se consume de la misma manera del endpoint predict/fred cambiando los campos y el endpoint.

== Herramientas
Otras herramientas para realizar pruebas o solicitudes a la API pueden ser Postman, SoapUI, RapidAPI, Rayuela, etc... Además, se puede consumir con diferentes lenguajes de preferencia.