= API : Instrucciones de uso
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Consumir API
La API tiene tres _endpoints_ para su uso. Además, al utilizar _swagger_ se puede acceder directamente mediante una interfaz gráfica para su uso manual.

=== Endpoints
Los *_endpoints_* son puntos de acceso o URLs específicas que se utilizan para realizar operaciones o solicitudes a través de la API. Cada _endpoint_ está diseñado para llevar a cabo una función específica y proporciona una forma estructurada y estandarizada de interactuar con la API.

Los *_endpoints_* pueden recibir solicitudes, como solicitudes HTTP-GET para obtener información o solicitudes HTTP-POST para enviar datos al servidor. En resumen, los *_endpoints_* actúan como interfaces que permiten a los clientes (como aplicaciones o usuarios) comunicarse de manera eficiente con la API y acceder a sus recursos o servicios de manera predefinida.

---
.Aclaración
[disclaimer]
----
FRED -> TUMORES CEREBRALES 

WINI -> NEUMONÍA 

LYSO -> RIÑONES

EN CASO DE PASARLE UN VALOR DISTINTO A *TRUE* EN LOS PARÁMETROS BOOLEANOS, SE LE ASIGNARÁ *FALSE* DE MANERA PREDETERMINADA. INCLUYENDO EN LOS CASOS DE ASIGNARLES VACÍO O NONE/NULL.
----

== Ping
Mediante una solicitud HTTP-GET se puede solicitar el _endpoint_, donde si está activo el servicio retorna un 200 y un JSON con el mensaje "API on!". Para acceder al _endpoint_ se debe agregar al dominio donde está la API subida _/ping_. EJ: `https://averiapi-4vtuhnxfba-uc.a.run.app/ping`

.ejemplo_get.js
[source,javascript]
----
fetch('https://averiapi-4vtuhnxfba-uc.a.run.app/ping')
  .then(response => {
    if (response.ok) {
      // El código de estado es 200 (OK)
      console.log('Código de estado: ' + response.status);
      return response.json();
    }
----

== Predict

=== */predict/fred*

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- image: Cual debe ser un archivo binario (imagen).

- id: Almacena un id.

- debilidad_focal: Almacena un booleano.

- convulsiones: Almacena un booleano.

- perdida_visual: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el mensaje con los % de cada clase del dominio. Ej:

{"glioma" : 0%,
 "meningioma" : 5%,
 "pituitary" : 0%,
 "no_tumor" : 95%}

Adjuntando el código de estado 200.

.ejemplo_post.js
[source,javascript]
----
const formData = new FormData();
formData.append('image', imagenFile); 
formData.append('debilidad_focal', True); 
formData.append('convulsiones', False); 
formData.append('perdida_visual', True); 

// Realizar la solicitud POST a la API
fetch('https://averiapi-4vtuhnxfba-uc.a.run.app/predict/fred', {
  method: 'POST',
  body: formData
})
  .then(response => {
    if (response.ok) {
      return response.text();
    } else {
      throw new Error('Error en la solicitud');
    }
  })
  .then(data => {
    console.log('Respuesta de la API:', data);
  })
  .catch(error => {
    console.error('Error al enviar la imagen:', error);
  });
----

=== */predict/wini*

Se realiza el mismo procedimiento del modelo **fred**, pero con distintos campos del JSON y cambiando el dominio por **wini**: `https://averiapi-4vtuhnxfba-uc.a.run.app/predict/wini`

- image: Debe ser un archivo binario (imagen).

- id: Almacena un id.

- puntada_lateral: Almacena un booleano.

- fiebre: Almacena un booleano.

- dificultad_respiratoria: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el mensaje con los % de cada clase del dominio. Ej:

{"pneumonia" : 1%,
 "no_pneumonia" : 99%
}

Adjuntando el código de estado 200.

=== */predict/lyso*

Se realiza el mismo procedimiento del modelo **fred** y **wini**, pero con distintos campos del JSON y cambiando el dominio por **lyso**: 'https://averiapi-4vtuhnxfba-uc.a.run.app/predict/lyso'

- image: Debe ser un archivo binario (imagen).

- id: Almacena un id.

- hermaturia: Almacena un booleano.

- dolor_lumbar: Almacena un booleano.

- fiebre: Almacena un booleano.

- dolor_abdominal: Almacena un booleano.

- perdida_peso: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el mensaje con los % de cada clase del dominio. Ej:

{
 "quiste" : 2%,
 "piedra" : 75%,
 "tumor" : 22%,
 "normal" : 1%
}

Adjuntando el código de estado 200.

== Feedback

=== */feedback/fred*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/feedback/fred`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- glioma: Almacena un booleano.
- meningioma: Almacena un booleano.
- pituitary: Almacena un booleano.
- no_tumor: Almacena un booleano.
- comment: Almacena un string.
 
Retornará un JSON con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */feedback/wini*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/feedback/wini`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- pneumonia: Almacena un booleano.
- no_pneumonia: Almacena un booleano.
- comment: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */feedback/lyso*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/feedback/lyso`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- quiste: Almacena un booleano.
- piedra: Almacena un booleano.
- tumor: Almacena un booleano.
- normal: Almacena un booleano.
- comment: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

== Delete

=== */delete/fred*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/delete/fred`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "DELETE ID: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/wini*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/delete/wini`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "DELETE ID: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/lyso*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/delete/lyso`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "DELETE ID: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 404.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/all*
ruta = `https://averiapi-4vtuhnxfba-uc.a.run.app/delete/all`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

model: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message": "ERROR! name is not string"}: En caso de que el parámetro model no sea un string. Adjunto con el código de estado 400.

- {"message": "ERROR! name model not exists"}:En caso de que el parámetro model no coincida con los nombres de los modelos "fred", "wini" o "lyso". Adjunto con el código de estado 404.

- {"message": "DELETE ALL ROW: model"}: En caso de que el parámetro model sea "fred", "wini" o "lyso". Adjunt con el código de estado 200.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.
== Herramientas
Otras herramientas para realizar pruebas o solicitudes a la API pueden ser Postman, SoapUI, RapidAPI, Rayuela, etc... Además, se puede consumir con diferentes lenguajes de preferencia.
