= API : Instrucciones de uso
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Consumir API
La API tiene tres _endpoints_ para su uso. Además, al utilizar _swagger_ se puede acceder directamente mediante una interfaz gráfica para su uso manual.

=== Endpoints
Los *_endpoints_* son puntos de acceso o URLs específicas que se utilizan para realizar operaciones o solicitudes a través de la API. Cada _endpoint_ está diseñado para llevar a cabo una función específica y proporciona una forma estructurada y estandarizada de interactuar con la API.

Los *_endpoints_* pueden recibir solicitudes, como solicitudes HTTP-GET para obtener información o solicitudes HTTP-POST para enviar datos al servidor. En resumen, los *_endpoints_* actúan como interfaces que permiten a los clientes (como aplicaciones o usuarios) comunicarse de manera eficiente con la API y acceder a sus recursos o servicios de manera predefinida.

---
.Aclaración
[disclaimer]
----
FRED -> TUMORES CEREBRALES 

WINI -> NEUMONÍA 

LYSO -> RIÑONES

EN CASO DE PASARLE UN VALOR DISTINTO A *TRUE* EN LOS PARÁMETROS BOOLEANOS, SE LE ASIGNARÁ *FALSE* DE MANERA PREDETERMINADA. INCLUYENDO EN LOS CASOS DE ASIGNARLES VACÍO O NONE/NULL.
----

== Ping
Mediante una solicitud HTTP-GET se puede solicitar el _endpoint_, donde si está activo el servicio retorna un 200 y un JSON con el mensaje "API on!". Para acceder al _endpoint_ se debe agregar al dominio donde está la API subida _/ping_. EJ: `http://averia.chickenkiller.com/ping`

.ejemplo_get.js
[source,javascript]
----
fetch('http://averia.chickenkiller.com/ping')
  .then(response => {
    if (response.ok) {
      // El código de estado es 200 (OK)
      console.log('Código de estado: ' + response.status);
      return response.json();
    }
----

== Predict

Mediante la imagen que se la pasa por parámetro y los datos extras, se realiza una predicción con el modelo seleccionado. Si todos los datos son válidos, se retorna un JSON con los % de la posible enfermedad. Posteriormente, se almacenan los datos ingresados, junto la imagen, para entrenar un nuevo modelo.

=== */predict/fred*

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- image: Cual debe ser un archivo binario (imagen).

- id: Almacena un id.

- debilidad_focal: Almacena un booleano.

- convulsiones: Almacena un booleano.

- perdida_visual: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el JSON con los % de cada clase del dominio. Ej:

{"glioma" : 0%,
 "meningioma" : 5%,
 "pituitary" : 0%,
 "no_tumor" : 95%}

Adjuntando el código de estado 200.

.ejemplo_post.js
[source,javascript]
----
const formData = new FormData();
formData.append('image', imagenFile); 
formData.append('debilidad_focal', True); 
formData.append('convulsiones', False); 
formData.append('perdida_visual', True); 

// Realizar la solicitud POST a la API
fetch('http://averia.chickenkiller.com/predict/fred', {
  method: 'POST',
  body: formData
})
  .then(response => {
    if (response.ok) {
      return response.text();
    } else {
      throw new Error('Error en la solicitud');
    }
  })
  .then(data => {
    console.log('Respuesta de la API:', data);
  })
  .catch(error => {
    console.error('Error al enviar la imagen:', error);
  });
----

=== */predict/wini*

Se realiza el mismo procedimiento del modelo **fred**, pero con distintos campos del JSON y cambiando el dominio por **wini**: `http://averia.chickenkiller.com/predict/wini`

- image: Debe ser un archivo binario (imagen).

- id: Almacena un id.

- puntada_lateral: Almacena un booleano.

- fiebre: Almacena un booleano.

- dificultad_respiratoria: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el JSON con los % de cada clase del dominio. Ej:

{"pneumonia" : 1%,
 "no_pneumonia" : 99%
}

Adjuntando el código de estado 200.

=== */predict/lyso*

Se realiza el mismo procedimiento del modelo **fred** y **wini**, pero con distintos campos del JSON y cambiando el dominio por **lyso**: 'http://averia.chickenkiller.com/predict/lyso'

- image: Debe ser un archivo binario (imagen).

- id: Almacena un id.

- hematuria: Almacena un booleano.

- dolor_lumbar: Almacena un booleano.

- fiebre: Almacena un booleano.

- dolor_abdominal: Almacena un booleano.

- perdida_peso: Almacena un booleano.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que no se le pase una imagen se retorna el mensaje : "message": "ERROR! image not found". Adjunto con el código de estado 404.

- En caso de que se le pase un id ya utilizado anteriormente se retorna el mensaje : "message": "ERROR! existing ID". Adjunto con el código de estado 400.

- En caso de que el id pasado no sea un entero retorna el mensaje: "message": "ERROR! ID is not int". Adjunto con el código de estado 400.

- En caso de que se le haya pasado un archivo que no sea .png, .jpg o .jpeg, retorna el mensaje: "message": "I'm a teapot!". con el código de estado 418.

- En caso de que haya sido correcto el consumo del modelo y los parámetros sean correctos, retorna el JSON con los % de cada clase del dominio. Ej:

{
 "quiste" : 2%,
 "piedra" : 75%,
 "tumor" : 22%,
 "normal" : 1%
}

Adjuntando el código de estado 200.

== Feedback

Al realizar una predicción mediante el _endpoint_ *Predict* se almacenaba la imagen y sus datos adicionales. En estos _endpoints_ de *Feedback* se le agregan datos nuevos a esa imagen. Esto se realiza vía la id sujeta a la imagen que se le asignó en *Predict*. 

El feedback se añade a la base de datos, adjuntandolo a la imagen con el mismo id.

=== */feedback/fred*
ruta = `http://averia.chickenkiller.com/feedback/fred`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- glioma: Almacena un booleano.
- meningioma: Almacena un booleano.
- pituitary: Almacena un booleano.
- no_tumor: Almacena un booleano.
- comment: Almacena un string.
 
Retornará un JSON con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */feedback/wini*
ruta = `http://averia.chickenkiller.com/feedback/wini`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- pneumonia: Almacena un booleano.
- no_pneumonia: Almacena un booleano.
- comment: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 2. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */feedback/lyso*
ruta = `http://averia.chickenkiller.com/feedback/lyso`

Mediante una solicitud HTTP-POST se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

- id_image: Almacena un int.
- quiste: Almacena un booleano.
- piedra: Almacena un booleano.
- tumor: Almacena un booleano.
- normal: Almacena un booleano.
- comment: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message" : "POST ACCEPTED"}: En caso de que los valores del JSON estén correctos, es decir, que el id_image sea un entero y que haya un solo valor booleano True entre los 4. Adjunto con el código de estado 200.

- {"message": "ERROR! there is more than one true value"}: En caso de que todos los campos del JSON que almacenan booleanos sean true. Adjunto con el código de estado 400.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

== Delete

Elimina los datos de una imagen y la misma imagen de la base de datos. Se le debe pasar un id existente. Se elimina solo la imagen del id correspondiente al modelo seleccionado.

Por otro lado también se puede eliminar todos los datos del modelo seleccionado, en el caso de consumir */delete/all*.

=== */delete/fred*
ruta = `http://averia.chickenkiller.com/delete/fred`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "ID DELETED: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/wini*
ruta = `http://averia.chickenkiller.com/delete/wini`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "DELETED ID: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/lyso*
ruta = `http://averia.chickenkiller.com/delete/lyso`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un json con los siguientes posibles mensajes:

- {"message": "DELETED ID: id"}, 200: En caso de que los valores del JSON estén correctos, es decir, que el id sea un entero y que haya encontrado el id en la base de datos. Adjunto con el código de estado 200.

- {"message": "ERROR! no exists ID"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

=== */delete/all*
ruta = `http://averia.chickenkiller.com/delete/all`

Mediante una solicitud HTTP-DELETE se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

model: Almacena un string.

Retornará un json con los siguientes posibles mensajes:

- {"message": "ERROR! name is not string"}: En caso de que el parámetro model no sea un string. Adjunto con el código de estado 400.

- {"message": "ERROR! name model not exists"}:En caso de que el parámetro model no coincida con los nombres de los modelos "fred", "wini" o "lyso". Adjunto con el código de estado 204.

- {"message": "DELETE ALL ROWS: model"}: En caso de que el parámetro model sea "fred", "wini" o "lyso". Adjunto con el código de estado 200.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

== Download

Descarga un archivo _.zip_ del modelo seleccionado. El _.zip_ contiene un csv y una carpeta images. El csv contiene los datos ingresados en los _endpoints_ de  *predict* y *feedback*, con la correspondiente imagen en la carpeta _images_.

=== */download/fred*
ruta = `http://averia.chickenkiller.com/download/fred`

Mediante una solicitud HTTP-GET se puede descargar un _zip_ con las imágenes almacenadas de los predict de fred. Además, adjunto con un csv con datos para un posible entrenamiento de un nuevo modelo.

Se consume de la misma manera del _endpoint_ `predict/fred` sin campos, cambiando el _endpoint_.

=== */download/wini*
ruta = `http://averia.chickenkiller.com/download/wini`

Mediante una solicitud HTTP-GET se puede descargar un _.zip_ con las imágenes almacenadas de los predict de wini. Además, adjunto con un csv con datos para un posible entrenamiento de un nuevo modelo.

Se consume de la misma manera del _endpoint_ `predict/fred` sin campos, cambiando el _endpoint_.

=== */download/lyso*
ruta = `http://averia.chickenkiller.com/download/lyso`

Mediante una solicitud HTTP-GET se puede descargar un _.zip_ con las imágenes almacenadas de los predict de lyso. Además, adjunto con un csv con datos para un posible entrenamiento de un nuevo modelo.

Se consume de la misma manera del _endpoint_ `predict/fred` sin campos, cambiando el _endpoint_.

== Retrieve

Mediante el id asociada a una imagen/predicción se obtienen los datos de la predicción y feedback en formato JSON. 

ruta = `http://averia.chickenkiller.com/retrieve`

Mediante una solicitud HTTP-GET se puede enviar al _endpoint_ un JSON, cual puede recibir los siguientes valores: 

id: Almacena un entero.

Retornará un JSON con los siguientes posibles mensajes:

- En caso de que exista el id en alguno de los 3 modelos, retorna el JSON con los datos del id asociado. Ej:

{
  "comment": "no tengo comentarios",
  "convulsiones": 0,
  "debilidad_focal": 1,
  "glioma": 1,
  "id": 7,
  "imagen": "images/7.png",
  "meningioma": 0,
  "model": "fred",
  "no_tumor": 0,
  "perdida_visual": 0,
  "pituitary": 0
}

Adjuntando el código de estado 200.

- {"message": "ERROR! ID not exists"}: En caso de que el id no exista dentro de nuestra base de datos, es decir, que no se haya realizado un predict con ese id o se haya eliminado anteriormente. Adjunto con el código de estado 204.

- {"message": "ERROR! ID is not int"}: En caso de que el parámetro pasado en el campo de id no sea un entero. Adjunto con el código de estado 400.

Se consume de la misma manera del _endpoint_ `predict/fred` cambiando los campos y el _endpoint_.

== Herramientas
Otras herramientas para realizar pruebas o solicitudes a la API pueden ser Postman, SoapUI, RapidAPI, Rayuela, etc... Además, se puede consumir con diferentes lenguajes de preferencia.