= TP Principal - Laboratorio de Construcción de Software: Sprint 3
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

Con la finalidad de ampliar el sistema y mejorar el desarrollo previo, nos pusimos los siguientes objetivos para este sprint:

1. Entrevistar un profesional para mejorar el modelo de detección de tumores cerebrales
2. Mejorar la API desarrollada en el sprint anterior
3. Desarrollar un modelo de detección de neumonía a partir de imágenes de rayos X de tórax
4. Realizar el deploy del modelo desarrollado

== Objetivos del documento

Luego de establecer los objetivos realizamos la división de tareas, para iniciar con el desarrollo y lograr el cumplimiento de todas las metas.

En este documento expondremos el trabajo realizado durante el sprint, la división de tareas realizada y los distintos problemas que se presentaron durante estas dos semanas.

== Metodología de trabajo

Debido a la naturaleza divergente de las tareas establecidas como objetivo, dividimos las tareas dependiendo de la semana.

.división de tareas del equipo de trabajo
[cols="3*", options="header"]
|===
|Encargado         |Tareas semana 1 |Tareas semana 2
|Villalba, Gastón  |Entrevistar experto, gestión|Corregir documentación previa, entrevista con neumonóloga pediátrica, gestión
|Ebertz, Ximena    |Búsqueda de datasets, entrevistar experto, búsqueda de información del problema, gestión|Creación del dataset, preparación de entorno de trabajo extra, CNN Manual, Xception, Transformada de Hough, gestión
|López, Gonzalo    |Búsqueda de datasets, búsqueda de información del problema|Creación del dataset, preparación de entorno de trabajo extra, EfficientNetV2, ResNet50V2, investigación sobre bases de datos
|Franco, Leandro   |Búsqueda de datasets, búsqueda de información del problema|Refinamiento API MDTC, preparación de entorno de trabajo extra, deploy y refinamiento de API MDEP
|Venditto, Pedro   |Búsqueda de datasets, entrevistar experto, búsqueda de información del problema|Refinamiento API MDTC, preparación de entorno de trabajo extra, entrevista con neumonólogra pediátrica
|===

Esta división se realizó teniendo en cuenta distintos *riesgos* y *cambios* a los que nos vimos expuestos.

=== Riesgos

Los riesgos se presentaron en la segunda semana del sprint. Tuvimos un miembro del equipo ausente dos días por motivos de estudio. A parte, nos encontramos con que el servidor con el cual trabajamos nos limitó la cantidad de horas mensuales a 30, siendo que antes contábamos con 150.

.riesgos enfrentados
[cols="8*", options="header"]
|===
|Riesgo        |Prob |Sev |Exp |Mitigación |Contingencia   |Resp |Sem
|Ausencia de miembros del equipo el 2023-10-18 y 2023-10-19 por motivos de estudio |3 |3 |9 |Definir reemplazantes, planificar ausencias |Reemplazos |GV, XE |2
|Dificultades en la integración con otros grupos del proyecto |2 |3 |6 |Establecer estándares de comunicación entre APIs |Comunicar por los medios acordados los inconvenientes surgidos |GV, XE |2
|Pérdida de posibilidad de trabajo en el entorno |1 |3 |3 |Backups periódicos, alternativas de entornos |Cambiar de entorno de trabajo, restablecer backup |GL, XE  
|===

=== Cambios

Durante el transcurso de la segunda semana, se presentó un cambio de alcance: la necesidad del feedback del médico. Nosotros lo considerabamos como un trabajo a futuro, por lo que nos generó un cambio en la planificación. Esto implica contar con una base de datos propia y generar un nuevo canal de comunicación entre nuestro equipo y el de datos. También, esta cambio implica la modificación de la API, ya que debemos recibir información que no teníamos en cuenta para esta instancia.

== Datos



== Modelos probados

* *ResNet:* 

* *SVM:* 

* *Xception:* 

* *CNN Manual:* 

* *Inception ResNetV2:* 

* *VGG16:* 

* *Transformada de Hough:* 

== Modelos descartados



== Modelo seleccionado



== Deploy


