= TP Principal - Laboratorio de Construcción de Software: Sprint 4
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

Con la finalidad de cumplir los objetivos núcleo del sistema, ampliarlo y mejorar el desarrollo previo, nos pusimos los siguientes objetivos para este sprint:

1. Implementar la base de datos requerida para el reentrenamiento del modelo.
2. Desarrollar un modelo de detección de enfermedades renales.
3. Integrar las soluciones del equipo con las del proyecto.

== Objetivos del documento

Luego de establecer los objetivos realizamos la división de tareas, para iniciar con el desarrollo y lograr el cumplimiento de todas las metas.

En este documento expondremos el trabajo realizado durante el sprint, la división de tareas realizada y los distintos problemas que se presentaron durante estas dos semanas.

== Metodología de trabajo

Como se puede ver en la división de tareas, el equipo trabajó en dos grupos.

.división de tareas del equipo de trabajo
[cols="2*", options="header"]
|===
|Encargado         |Tareas
|Villalba, Gastón  |Corregir documentación previa, gestión
|Ebertz, Ximena    |Búsqueda de datasets, búsqueda de información del problema, creación del dataset, CNN Manual, Xception, definición de arquitectura MDER, conexión con equipo de datos, refinamiento de modelo, gestión
|López, Gonzalo    |Investigación sobre BBDD, búsqueda de datasets, búsqueda de información del problema, creación del dataset, subir dataset de riñones a Kaggle, ResNet50V2, SVM
|Franco, Leandro   |Investigación sobre BBDD, capacitación en bases de datos, implementación de BBDD con API, deploy modelo de enfermedades renales, refinamiento API, conexión con equipo de datos
|Venditto, Pedro   |Capacitación en bases de datos, implementación de BBDD con API, investigación FileServer, implementación FileServer, deploy Modelo de Enfermedades Renales, refinamiento API, conexión con equipo de datos
|===

Se definió que Franco, Leandro y Venditto, Pedro trabajarían desarrollando la base de datos y actualizando la API para cumplir con el primer objetivo. Por otra parte, Ebertz, Ximena y López, Gonzalo trabajarían principalmente desarrollando el modelo, para cumplir con el segundo objetivo. Luego, se trabajaría en conjunto para la integración de nuestra API con el resto del proyecto, y así cumplir con el tercer objetivo.

== Datos

Determinamos que los siguientes datasets serían útiles para nuestro trabajo:

* Dataset 1: https://www.kaggle.com/datasets/nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone[CT KIDNEY DATASET: Normal-Cyst-Tumor and Stone]
* Dataset 2: https://www.kaggle.com/datasets/mohammedrizwanmalik/kidney-stones-mri-and-ct-scans[Kidney Stones Mri and CT scans]
* Dataset 3: https://www.kaggle.com/datasets/raagbhutani/kidneystone[KidneyStone]
* Dataset 4: https://www.kaggle.com/datasets/arjunbasandrai/medical-scan-classification-dataset[Medical Scan Classification Dataset]

Como en el sprint previo, creamos un dataset y lo subimos a Kaggle. El dataset se encuentra https://www.kaggle.com/datasets/gonzajl/riones-cyst-stone-tumor-normal-dataset[acá].

== Modelos probados

* *ResNet50V2:* Este modelo alcanzó un porcentaje de precisión A en las pruebas, para X imágenes.

* *CNN Manual:* Este modelo alcanzó un porcentaje de precisión A en las pruebas, para X imágenes.

== Modelos descartados

== Modelo seleccionado

== Entrevistas

== Deploy

== Base de datos