= TP Principal - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Torrez Mauro <>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

La Inteligencia Artificial o _IA_ es un poderoso campo de estudio que está en constante crecimiento. Cada día, los modelos de Inteligencia Artificial evolucionan y se incorporan en nuestro día a día, funcionando como una herramienta de trabajo potente.

Existen muchos campos donde la Inteligencia Artificial se está desarrollando: detección de imágenes, texto, audio, etcétera. Resulta lógico pensar que se pueden desarrollar herramientas para campos más específicos, como medicina, finanzas, o investigación.

== Objetivos del proyecto

Nuestro objetivo es, mediante la aplicación de tecnologías relacionadas a las inteligencias artificiales, implementar una aplicación que pueda ayudar a nuestros profesionales del área de la medicina a lograr un diagnóstico más rápido y preciso sobre alguna enfermedad o malestar en específico.

Para esto, realizaremos tareas de investigación, de análisis de datos y de desarrollo, entre otras.

== Objetivos del documento

El principal objetivo de este documento es especificar las decisiones que se tomen en los días previos al inicio del proyecto; tales como la distribución de roles de trabajo, los posibles riesgos del equipo, el tema a trabajar, las metodologías que se utilizarán, entre otras cosas relacionadas a la organización necesaria del proyecto.

== Metodología de trabajo
Utilizaremos Scrum para trabajar y coordinar al equipo. A está metodología la modificaremos para coordinarla con las preferencias del equipo para optimizarla.

- Scrum Daily cada 2 días: Esto se realizará así porque los integrantes del equipo tienen tiempos diferentes y no harán tiempo para tener un avance considerable para plantearlo en las Daily. Por incovenientes o bloqueo de un integrante, en el día que no hay daily, se hablará por un canal de comunicación interna.

== Equipo de trabajo y roles

Los roles que se utilizarán en el equipo son los siguientes:

[cols="3*",options="header"]
|===
|Rol            |Encargado         |Suplente

|Scrum Master   |Villalba, Gastón  |Ximena Ebertz
|Líder Técnico  |Ebertz, Ximena    |
|Desarrollador  |Franco, Leandro   |
|Desarrollador  |Torrez, Mauro     |
|Desarrollador  |López, Gonzalo    |
|Desarrollador  |Venditto, Pedro   |
|===

//modificar roles

== Gestión

=== Plan de comunicaciones

Nuestro medios de comunicación son:

*Gather* Es una plataforma que nos permite tener una oficina virtual, donde cada uno tiene su personaje dentro de esta oficina. La utilizamos porque no tiene límites de tiempo, permite la comunicación a través de voz y es menos monótona que otras plataformas como Meet. Es una vía de comunicación formal que empleamos para las reuniones diarias.

*WhatsApp*  Es un medio de comunicación informal que utilizamos para coordinar los horarios de las reuniones en Gather y discutir cuestiones relacionadas con el proyecto que no requieran la presencia de todo el equipo en ese momento. Se trata de un método de comunicación asincrónica.

*Telegram* Similar al uso que le damos a WhatsApp, pero para relacionarlos con los demás equipos de trabajo. Principalmente es para coordinar reuniones o solicitar ayuda con alguna cuestión del proyecto.

*Mail* En caso de que sea necesario, por algún incoveniente externo que no permita las vías convencionales, utilizaremos el mail de los integrantes para coordinar al equipo. Además, es la principal vía para comunicarnos con nuestro Product Owner.


=== Riesgos

Matriz de evaluación de riesgos.

[cols="7*",options="header"]
|===
|Descripción                         |Probabilidad de que ocurrencia         |Severidad      |Exposición al riesgo|Acciones para mitigarlos|Contingencia|Responsable

|Falta de motivación de un integrante|2|2|4|Motivación hacía el integrante|llevarlo a una discoteca y prometerle un salario en dolares (?)| Villalba, Gastón
|||||||
|||||||
|||||||
|||||||
|||||||
|||||||
|===

=== Administración en el Manejo de bugs

Utilizaremos Los _Issue_ de GitHub para reportar bugs. Además se agregarán al Jira de los PO, SM y LT. Posteriormente a un (Trello/Jira) de nuestro equipo para manejar el estado el bug.

=== Administración de Cambios

Tras recibir una petición de cambio, documentaremos las nuevas funcionalidades que nos solitan y posteriormente lo agregaremos al backlog. Esta nueva modificación se evaluará, se estimará con los integrantes del proyecto, se modificará la WBS, Diccionario y se agregará al Sprint.


== Tecnologías

Las tecnologías a utilizar serán las siguientes:

- *Google Collab* para el desarrollo del modelo de IA, ya que el entorno de trabajo contiene todo lo necesario.
- *Python* como lenguaje de programación, por su simplicidad y utilidad en el desarrollo de este tipo de modelos.
- *TensorFlow - Keras* como biblioteca principal de desarrollo, ya que provee distintas funcionalidades para la creación de modelos de IA.
- *NumPy* debido a la necesidad de trabajar las imágenes como arrays multidimensionales o _tensores_.
- *Pandas* ya que permite obtener información de archivos .csv
- *cv2* como biblioteca de lectura y procesamiento de imágenes.
- *matplotlib.pyplot* para generar gráficos.
- *GitHub* como repositorio de trabajo.

=== Repositorio de GitHub

https://github.com/ximeeb/tp-principal-grupo-0-lcs.git

Acá podríamos poner enlaces
