= TP Principal - Laboratorio de Construcción de Software: Sprint 3
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

Con la finalidad de ampliar el sistema y mejorar el desarrollo previo, nos pusimos los siguientes objetivos para este sprint:

1. Entrevistar un profesional para mejorar el modelo de detección de tumores cerebrales
2. Mejorar la API desarrollada en el sprint anterior
3. Desarrollar un modelo de detección de neumonía a partir de imágenes de rayos X de tórax
4. Realizar el deploy del modelo desarrollado

== Objetivos del documento

Luego de establecer los objetivos realizamos la división de tareas, para iniciar con el desarrollo y lograr el cumplimiento de todas las metas.

En este documento expondremos el trabajo realizado durante el sprint, la división de tareas realizada y los distintos problemas que se presentaron durante estas dos semanas.

== Metodología de trabajo


.división de tareas del equipo de trabajo
[cols="2*", options="header"]
|===
|Encargado         |Tarea
|Villalba, Gastón  |
|Ebertz, Ximena    |
|López, Gonzalo    |
|Franco, Leandro   |
|Venditto, Pedro   |
|===

== Datos



== Modelos probados

* *ResNet:* 

* *SVM:* 

* *Xception:* 

* *CNN Manual:* 

* *Inception ResNetV2:* 

* *VGG16:* 

* *Transformada de Hough:* 

== Modelos descartados



== Modelo seleccionado



== Deploy


