= TP Pincipal - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <>; López Gonzalo <gonzagonzalopez20@gmail.com>; Torrez Mauro <>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción
En este documento se llevará a cabo la introducción al tema que nuestro grupo trabajará durante el resto de la cursada. En donde, mediante la aplicación de tecnologías relacionadas a las inteligencias artificiales (IA), buscaremos implementar una aplicación que pueda ayudar a nuestros profesionales del área de la medicina a lograr un diagnóstico más rápido y preciso sobre alguna enfermedad o malestar en específico.

== Objetivos del documento

== Equipo de trabajo y roles
=== Scrum Master
Villalba, Gastón

=== Líder Técnico
Ebertz, Ximena

=== Relleno de Naruto
* Franco, Leandro
* Torrez, Mauro
* Venditto, Pedro


== Metodología de desarrollo

== Gestión

== Tecnologías

Acá podríamos poner enlaces
