= Modelo Xception: Entrenamiento y pruebas
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Transformada de Hough

La transformada de Hough es una técnica de procesamiento de imágenes que permite detectar figuras en una imagen, tales como líneas, elipses y círculos. No es un modelo de inteligencia artificial, por lo que no se debe entrenar. Es decir, se puede importar y utilizar para una imagen en específico.

La biblioteca OpenCV cuenta con un dos implementaciones de esta técnica: `HoughCircles` y `HoughLines`. La primera es utilizada para detectar círculos en una imagen, y la segunda es para detectar líneas.

Para nuestro dominio, la implementación que podría ser útil es `HoughCircles`, debido que estos círculos pueden ser tumores cerebrales. Por este motivo, realizamos unas pruebas en base a nuestro https://www.kaggle.com/datasets/gonzajl/tumores-cerebrales-mri-dataset/data[dataset].

== Pruebas

== Conclusión