= TP Principal - Laboratorio de Construcción de Software: Sprint 2
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

Como ya se mencionó, el objetivo del proyecto es desarrollar un software que permita diagnosticar enfermedades de distintas partes del cuerpo a través de imágenes. El software está dirigido a todos profesionales de la salud que requieran utilizarlo.

Para este sprint, nuestro objetivo es desarrollar y hacer el deploy de un modelo que determine si un paciente tiene o no un tumor, y de qué tipo, a través de imágenes de resonancia magnética.


== Objetivos del documento

Una vez establecido el objetivo del trabajo, procedimos a realizar las tareas necesarias para el preprocesamiento de datos y el entrenamiento de distintos modelos, tantos preentrenados como manuales.

En este documento expondremos cómo preparamos los datos, qué modelos entrenamos y cuál es el elegido para nuestro problema. También explicaremos las distintas decisiones tomadas durante el desarrollo.

== Datos

Para la detección de tu

== Modelos probados

* ResNet

* SVM

* Xception

* CNN Manual

* Inception ResNet

* VGG16

* Transformada de Hough

== Modelos descartados

* Mask R CNN

* VGG19

