= Plataformas de despliegue: Creación de una API para el uso de los modelos
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [2.8cm, 2.8cm, 2.8cm, 2.8cm]

== Plataforma

Una plataforma de despliegue, en términos sencillos, se refiere a un conjunto de instrumentos y recursos para llevar a cabo la implementación y puesta en funcionamiento de aplicaciones y/o bases de datos en entornos de producción en la nube. 

Existen plataformas que se denominan PaaS (Platform as a Service) estos proporciona una plataforma y un entorno completo para el desarrollo, implementación y administración de aplicaciones en la nube. En este modelo, los proveedores de servicios en la nube ofrecen una plataforma que incluye sistemas operativos, entornos de desarrollo, herramientas de base de datos y servicios de alojamiento, lo que permite a los desarrolladores centrarse en escribir código y crear aplicaciones sin preocuparse por la infraestructura subyacente.

=== Fly.io

Fly.io nos permite trabajar con varios lenguajes y frameworks, porque permite trabajar con Docker. Aunque tiene opciones para el despliegue rápido de ciertos frameworks y lenguajes.
Además, permite alojar bases de datos como PostgreSQL, MySQL, Sqlite y Redis.

Por otro lado, ofrece un programa de consola llamada flyCTL que permite registrarse en el sitio, realizar el deploy e incluyendo la posibilidad de realizarlo sin estar subido a un repositorio Git.

Su servicio gratuito incluye:

* 3 maquinas virtuales con cpu compartida.
* 256 MB de ram.
* 3 GB de almacenamiento persistente.
* 160 GB de transferencias de datos (outbound).

Tutorial para realizar un deploy de una aplicación Flask: https://fly.io/docs/languages-and-frameworks/python/

=== Render

Render permite trabajar con Docker, es decir, permite trabajar con los lenguajes que soporten Docker. Pero tiene opciones de despliegue rápido para ciertos lenguajes como Python, Rails NodeJS, Ruby, Elixir, PHP y Go. 

Además, permite alojar bases de datos como PostgreSQL y Redis.

Su servicio gratuito incluye:

* Cpu compartida. 
* 512 MB de ram.
* 750 Horas totales de instancias de los servicios al mes, o sea, 31 días activo con solo 1 aplicación. En cambio, si hay dos aplicaciones funcionando al mismo tiempo, se repartirían los días quedando 15 días activos durante el mes. A principio de cada mes se reinicia el contador de horas.
* 100 GB de transferencias de datos (outbound).
* 500 Minutos de compilación en la nube de la aplicación.

Hay una desventaja en Render con la actividad de la aplicación: Si se deja de utilizar durante un tiempo, el servidor entra en un estado de reposo. Por lo tanto, si se dejo de utilizar la aplicación durante un cierto tiempo, cada vez que entra en el estado de reposo y se intenta utilizar el servicio, se debe esperar que la aplicación inicie nuevamente. Esto se puede solucionar con un bot que haga un llamado a una API de la aplicación periodicamente para que el servicio se mantenga activo, pero consume el outbound.

=== Railway

Railway es una de las plataformas más nuevas. Admite lenguajes como Javascript/Typescript, Python, PHP, Golang, Ruby, Rust, simplemente importando el proyecto desde un repositorio Github y el despliegue es muy rapido (en menos de 1 minuto). También tiene más de 75 templates para iniciar el proyecto. Además permite Docker, por ende soporta los lenguajes que puedan utilizar Docker.

También ofrece subir bases de datos gratuitas en MySQL, PostgreSQL, Mongodb y Redis. Estos mismos sin REGISTRARSE &#x1F640; &#x1F640; &#x1F640;.

Por otro lado, ofrece un CLI para su uso mediante linea de comandos.

Su servicio gratuito incluye:

* 2 contenedores.
* 512 Mb de ram por contenedor.
* 1 GB de almacenamiento persistente.
* Railway mensualmente nos proporcionara un saldo gratuito de 5 dólares, con el que tendremos disponibles 500 horas de uso de una máquina sencilla, estas cuentan desde que el proyecto queda activo y se descontaran por cada hora activa que tengas un proyecto funcionando.

=== FL0
FL0 es otro PaaS similar a los anteriores mencionados. Este servicio admite lenguajes como .Net, GO, Java, Node.js, PHP, Python, Ruby, Rust y Static Sites. Además, existe la posibilidad de utilizar Docker. La manera de realizar el Deploy es una de la más sencillas y aún más si se cuenta con un _Dockerfile_, Simplemente es Linkear una cuenta de GitHub y seleccionar el proyecto que se quiera subir. Por otro lado, también permite tener una Base de datos PostgreSQL.

Su servicio gratuito incluye:

* Un solo proyecto activo siempre.
* CPU compartida.
* 10 GB de transferencias de datos (outbound).
* 1 GB de almacenamiento.
* 14 días de Logs.
* 3 GB de almacenamiento en caso de levantar una Base de datos.

== Conclusión

Estás plataformas PaaS no son las únicas para realizar un despliegue de nuestra API, pero consideramos que son las más sencillas de utilizar y que cumplen con los requisitos que estamos buscando. 

Tras barajar varias opciones y documentar las 4 más potables, decidimos utilizar FL0.

Decidimos utilizar FL0 por estar activa 24/7 al mes. Sus otros beneficios de su capa gratuita es similar a los demás servicios.

Aunque nuestra plataforma final es FL0 tenemos como alternativas a Railway que permite 500 horas por mes, es decir, 21 días aproximadamente. Por lo último dicho, Railway queda como segunda opción. 

Por último, tenemos tercer opción: Render, que permite 750 horas activa la aplicación por mes, pero tras un tiempo de desuso se entra en un estado de hibernación.  