= Inception ResNet V2
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [2.8cm, 2.8cm, 2.8cm, 2.8cm]

== ¿Qué es Inception ResNet V2?

Es una arquitectura de red neuronal profunda que combina las ideas clave de las redes Inception y las redes ResNet. La combinación de estas dos arquitecturas ha demostrado ser eficaz para mejorar el rendimiento y la eficiencia de las redes neuronales

== Modelo Implementado

Nuestro modelo trabaja con un dataset creado por nosotros en base a otros dataset obtenidos de Kaggle. Nuestro dataset puede obtenerse del siguiente link: "https://www.kaggle.com/datasets/gonzajl/tumores-cerebrales-mri-dataset".

La implementación del modelo en este caso es una aplicación del modelo pre-entrenado llamado Inception ReNet V2. Este modelo es uno de los más pesados computacionalmente, por lo que el entrenamiento del mismo se realizó con una cantidad de imágenes menor a otros modelos y en una sola vuelta de entrenamiento. Aun así, este modelo dio resultados que merecen ser tenidos en cuenta a la hora de elegir un modelo.

== Entrenamiento

Como se dijo anteriormente, el entrenamiento se realizó con 3.250 imágenes en cada una de las clases, es decir, un total de 13.000 imágenes. Esta cantidad de imágenes luego se dividió en 10.400 imágenes de entrenamiento y 2600 de prueba. La división utilizada en este caso fue de una relación 80% entrenamiento y 20% testing.

== Resultados obtenidos

Epoch 1

loss: 0.2602 - categorical_accuracy: 0.9130 - val_loss: 0.4122 - val_categorical_accuracy: 0.8604

== Resultados por clase

Cantidad de predicciones: 2600
Etiquetas:   [G,  M,  P,  N]
Total:       [600, 637, 459, 904]
Correctas:   [533, 567, 459, 678]
Incorrectas: [67, 70, 0, 226]



