@startwbs BIOS
<style>
wbsDiagram {
    .pink{
        BackgroundColor Pink
    };
    .orange{
        BackgroundColor Orange
    };
    .violet{
        BackgroundColor Thistle 
    };
    .blue{
        BackgroundColor SkyBlue
    };
    .green{
        BackgroundColor LimeGreen
    };
    .new {
        BackgroundColor Khaki
    }
};
</style>

* 1 - BIOS <<pink>>

** 1.0 - Gestión <<orange>>
*** 1.0.0 - Capacitación en herramientas de gestión <<green>>
*** 1.0.1 - Sprint 1 <<violet>>
**** 1.0.1.1 - Riesgos <<green>>
**** 1.0.1.2 - Cambios <<green>>
**** 1.0.1.A - Informe <<green>>
**** 1.0.1.B - Comunicación <<green>>
**** 1.0.1.C - Gestión técnica <<green>>

*** 1.0.2 - Sprint 2 <<violet>>
**** 1.0.2.1 - Riesgos <<green>>
**** 1.0.2.2 - Cambios <<green>>
**** 1.0.2.A - Refinar documentación <<green>>
**** 1.0.2.B - Informe  <<green>>
**** 1.0.2.C - Comunicación <<green>>
**** 1.0.2.D - Gestión técnica <<green>>

*** 1.0.3 - Sprint 3 <<violet>>
**** 1.0.3.1 - Riesgos <<green>>
**** 1.0.3.2 - Cambios <<green>>
**** 1.0.3.A - Refinar documentación <<green>>
**** 1.0.3.B - Informe <<green>>
**** 1.0.3.C - Comunicación <<green>>
**** 1.0.3.D - Gestión técnica <<green>>

*** 1.0.4 - Sprint 4 <<violet>>
**** 1.0.4.1 - Riesgos <<green>>
**** 1.0.4.2 - Cambios <<green>>
**** 1.0.4.A - Refinar documentación <<green>>
**** 1.0.4.B - Informe <<green>>
**** 1.0.4.C - Comunicación <<green>>
**** 1.0.4.D - Gestión técnica <<green>>

*** 1.0.5 - Sprint 5 <<violet>>
**** 1.0.5.1 - Riesgos <<green>>
**** 1.0.5.2 - Cambios <<green>>
**** 1.0.5.A - Refinar documentación <<green>>
**** 1.0.5.B - Informe <<green>>
**** 1.0.5.C - Comunicación <<green>>
**** 1.0.5.D - Gestión técnica <<green>>

*** II - Corregir documentación previa <<new>>
*** FINN - Presentación Final <<new>>

** 1.1 - Investigación <<orange>>
*** 1.1.0 - Comprender los requerimientos <<green>>
*** 1.1.1 - Documentación de capacitación interna <<green>>
*** 1.1.2 - Lectura relacionada con la clasificación de imágenes médicas <<violet>>
**** 1.1.2.A - Clasificación de tumores cerebrales <<green>>
**** 1.1.2.B - Clasificación de enfermedades pulmonares <<green>>
**** 1.1.2.C - Clasificación de sprint 4 <<green>>

*** 1.1.3 - Entrevistar expertos <<violet>>
**** 1.1.3.A - Profesional neurólogo <<green>>
**** 1.1.3.B - Neunomóloga pediátrica <<green>>
**** 1.1.3.C - Profesional urólogo <<green>>

*** 1.1.4 - Recopilación de datos <<violet>>
**** 1.1.4.A - Dataset tumores cerebrales <<green>>
**** 1.1.4.B - Dataset enfermedades pulmonares <<green>>
**** 1.1.4.C - Dataset enfermedades renales <<green>>

** 1.2 - Modelos de IA <<orange>>

*** 1.2.1 - Procesamiento de imágenes <<violet>>
**** 1.2.1.1 - Investigación de técnicas de procesamiento <<green>>
**** 1.2.1.2 - Refinamiento de datos <<blue>>
***** 1.2.1.2.A - Ref. tumores cerebrales <<green>>
***** 1.2.1.2.B - Ref. pulmones <<green>>
***** 1.2.1.2.C - Ref. riñones <<green>>

**** 1.2.1.3 - Nivelación de clases <<blue>>
***** 1.2.1.3.A - Niv. tumores cerebrales <<green>>
***** 1.2.1.3.B - Niv. pulmones <<green>>
***** 1.2.1.3.C - Niv. riñones <<green>>

**** 1.2.1.A - Subir dataset MDTC <<green>>
**** 1.2.1.B - Subir dataset MDEP <<green>>
**** 1.2.1.C - Subir dataset MDER <<green>>

*** 1.2.2 - Implementación de modelos <<violet>>
**** 1.2.2.0 - Determinar plataforma de cómputo <<green>>
**** 1.2.2.1 - Investigación de modelos preentrenados <<green>>
**** 1.2.2.2 - Desarrollo de modelos <<blue>>
***** 1.2.2.2.A - Modelo de Detección de Tumores Cerebrales <<green>>
***** 1.2.2.2.X - Definición de arquitectura MDTC <<green>>
***** 1.2.2.2.B - Modelo de Detección de Enfermedades Pulmonares <<green>>
***** 1.2.2.2.Y - Definición de arquitectura MDEP <<green>>
***** 1.2.2.2.C - Modelo de Detección de Enfermedades Renales <<green>>
***** 1.2.2.2.Z - Definición de arquitectura MDER <<green>>
**** III - Preparación de entorno de trabajo extra <<new>>

*** 1.2.3 - Despliegue de modelos <<violet>>
**** 1.2.3.1 - Determinar plataforma de deploy <<green>>
**** 1.2.3.A - Deploy Modelo de Detección de Tumores Cerebrales <<green>>
**** 1.2.3.B - Deploy Modelo de Detección de Enfermedades Pulmonares <<green>>
**** 1.2.3.C - Deploy Modelo de Detección de Enfermedades Renales <<green>>
**** 1.2.3.D - Generar API de prueba <<green>>
**** I - Documentación API <<new>>

** 1.3 - Validación <<orange>>
*** 1.3.1 - Integración con otros equipos <<green>>
*** 1.3.A - Refinamiento de API MDTC <<green>>
*** 1.3.B - Refinamiento de API MDEP <<green>>
*** 1.3.C - Refinamiento de API MDER <<green>>
*** IV - Soporte <<new>>
*** V - Monitoreo de Logs <<new>>

** 1.4 - Reentrenamiento <<orange>>
*** 1.4.1 - Investigación sobre bases de datos <<green>>
*** 1.4.2 - Capacitación en bases de datos <<green>>
*** 1.4.3 - Integración de BBDD con API <<green>>
*** 1.4.4 - Conexión con equipo de datos <<green>>

** 1.A - Reuniones <<orange>>
*** 1.A.1 - Reunión Formal 1 <<green>>
*** 1.A.2 - Reunión Formal 2 <<green>>
*** 1.A.3 - Reunión Formal 3 <<green>>
*** 1.A.4 - Reunión Formal 4 <<green>>
*** 1.A.5 - Reunión Formal 5 <<green>>
*** 1.A.6 - Clase de consultas 1 <<green>>
*** 1.A.7 - Clase de consultas 2 <<green>>
*** 1.A.8 - Clase de consultas 3 <<green>>
*** 1.A.9 - Clase de consultas 4 <<green>>
*** 1.A.10 - Clase de consultas 5 <<green>>
*** 1.A.11 - Clase de consultas 6 <<green>>
*** 1.A.12 - Clase de consultas 7 <<green>>
*** 1.A.13 - Clase de consultas 8 <<green>>
*** 1.A.14 - Clase de consultas 9 <<green>>
*** 1.A.15 - Clase de consultas 10 <<green>>
*** 1.A.16 - Clase de consultas 11 <<green>>
*** 1.A.17 - Clase de consultas 12 <<green>>
*** 1.A.18 - Sprint 1 Planning <<green>>
*** 1.A.19 - Sprint 2 Planning <<green>>
*** 1.A.20 - Sprint 3 Planning <<green>>
*** 1.A.21 - Sprint 4 Planning <<green>>
*** 1.A.22 - Sprint 5 Planning <<green>>
*** 1.A.23 - Daily Scrum <<green>>
*** 1.A.24 - Retrospective 1 <<green>>
*** 1.A.25 - Retrospective 2 <<green>>
*** 1.A.26 - Retrospective 3 <<green>>
*** 1.A.27 - Retrospective 4 <<green>>
*** 1.A.28 - Retrospective 5 <<green>>
@endwbs