= API-CSV : Implementación de CSV con nuevos datos
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== CSV

Un archivo CSV (Comma-Separated Values) es un formato de archivo utilizado para almacenar datos tabulares en forma de texto plano. En un archivo CSV, los datos se organizan en filas y columnas, y cada fila representa un registro o una entrada de datos, mientras que las columnas representan campos o atributos. Ej:

---
.Ejemplo CSV
[disclaimer]
----
id,nombre,apellido
1,carlos,menem
2,ricardo,fort
3,leandro,franco
----

== Implementación

Se decidió utilizar CSV como medio para almacenar los datos ingresados en los endpoints de predict y feedback porque los datos que planeamos almacenar no son de gran volumen. El CSV nos permite, en caso de ser necesario, migrar los datos a una base de datos de una manera sencilla.

=== ID existente

Existe una función booleana que busca si el ID pasado como parámetro existe o no. Esta fue creada porque necesitábamos saber si existía una fila para evitar sobrescribir datos anteriores, lo que nos permite no borrar datos por error.

.exists_id
[source,python]
----

def exists_id(csv, id):
    df = pd.read_csv(csv)
    list_id = df['id'].tolist()
    return id in list_id

----

=== Agregar datos del predict

Existen dos funciones (y posiblemente tres) que almacenan en un su CSV correspondiente los datos del predict. Se deja los espacios en blanco los datos que se le ingresaran durante el feedback.

Lee el archivo CSV correspondiente al modelo y crea una nueva fila con los datos pasados por parámetros.

El parámetro 'imagen' es la ruta donde está almacenada, en el proyecto, la imagen que fue ingresada para predecir. Los demás parámetros son todos valores enteros. Cada valor entero representa un valor booleano, es decir, si es 1 se interpreta como verdadero y si es 0, falso. Esto se hace de esta manera para facilitar el entrenamiento del modelo en caso de realizarse con este CSV.

.append_predict_wini
[source,python]
----

def append_predict_wini(id, imagen, puntada_lateral, fiebre, dificultad_respiratoria):
    df = pd.read_csv("csv/wini.csv")
    new_row = pd.DataFrame({'id': [id], 'imagen': [imagen], 'puntada_lateral': [puntada_lateral],
                            'fiebre': [fiebre], 'dificultad_respiratoria': [dificultad_respiratoria],
                            'pneumonia': [''], 'no_pneumonia': ['']})

    df = pd.concat([df, new_row], ignore_index=True)
    df.to_csv('csv/wini.csv', index=False, float_format='%.0f')

----

De alguna forma, al momento de pasarle un entero a la función, lo transforma en float. Entonces, con _`float_format = '%.0f'_, lo convertimos a entero para mejor entendimiento.