= API-CSV : Implementación de CSV con nuevos datos
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Franco Leandro <leandro00fr@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>; Venditto Pedro <pedrovenditto41@gmail.com>; Villalba Gastón <gastonleovillalba@gmail.com>;
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== CSV

Un archivo CSV (Comma-Separated Values) es un formato de archivo utilizado para almacenar datos tabulares en forma de texto plano. En un archivo CSV, los datos se organizan en filas y columnas, y cada fila representa un registro o una entrada de datos, mientras que las columnas representan campos o atributos. Ej:

---
.Ejemplo CSV
[disclaimer]
----
id,nombre,apellido
1,carlos,menem
2,ricardo,fort
3,leandro,franco
----

== Implementación

Se decidió utilizar CSV como medio para almacenar los datos ingresados en los endpoints de predict y feedback porque los datos que planeamos almacenar no son de gran volumen. El CSV nos permite, en caso de ser necesario, migrar los datos a una base de datos de una manera sencilla.

=== ID existente

Existe una función booleana que busca si el ID pasado como parámetro existe o no. Esta fue creada porque necesitábamos saber si existía una fila para evitar sobrescribir datos anteriores, lo que nos permite no borrar datos por error.

.exists_id
[source,python]
----
def exists_id(csv, id):
    df = pd.read_csv(csv)
    list_id = df['id'].tolist()
    return id in list_id

----